import { Cloud, CloudOff, Cog, Loader2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useMutation, useQuery } from '@tanstack/react-query';
import {
  api,
  type BedType,
  type PresetRef,
  type PresetSource,
  type SliceBundleSpec,
  type SliceJobProgress,
  type SliceRequest,
  type SlicerBundle,
  type SlicerCloudStatus,
  type UnifiedPreset,
  type UnifiedPresetsResponse,
} from '../api/client';
import { useSliceJobTracker } from '../contexts/SliceJobTrackerContext';
import { useToast } from '../contexts/ToastContext';
import { SlicePlateSelector } from './SlicePlateSelector';
import type { PlateFilament } from '../types/plates';
import { normalizeColorForCompare, colorsAreSimilar } from '../utils/amsHelpers';
import {
  BundleStringDropdown,
  PresetDropdown,
  PresetSourceControl,
} from './preset-picker/PresetTripletPicker';
import {
  TIER_ORDER as SLICE_MODAL_TIER_ORDER,
  matchesOwnerFilter,
  type OwnerFilter,
  type Slot,
} from './preset-picker/presetPickerUtils';
import { BedTypePicker } from './preset-picker/BedTypePicker';
import { SlicerPicker, type SlicerKind } from './preset-picker/SlicerPicker';

export type SliceSource =
  | { kind: 'libraryFile'; id: number; filename: string }
  | { kind: 'archive'; id: number; filename: string };

interface SliceModalProps {
  source: SliceSource;
  onClose: () => void;
}

function pickDefault(by: UnifiedPresetsResponse, slot: Slot): PresetRef | null {
  for (const tier of SLICE_MODAL_TIER_ORDER) {
    const list = by[tier][slot];
    if (list.length > 0) {
      return { source: list[0].source, id: list[0].id };
    }
  }
  return null;
}

const TIER_BONUS: Record<PresetSource, number> = {
  local: 1.5,
  cloud: 1.0,
  standard: 0.5,
};

function pickFilamentForSlot(
  by: UnifiedPresetsResponse,
  required: { type: string; color: string },
): PresetRef | null {
  // Score every filament preset against the plate slot's required (type,
  // colour) and pick the highest. Mirrors the AMS slot-mapping match in the
  // print/schedule modal: type match dominates, exact-colour-match bumps over
  // similar-colour-match, and a small per-tier bonus breaks ties so cloud
  // user customisations win over standard bundled fallbacks of equal merit.
  const reqType = required.type.trim().toUpperCase();
  const reqColor = normalizeColorForCompare(required.color);

  let best: { ref: PresetRef; score: number } | null = null;
  for (const tier of SLICE_MODAL_TIER_ORDER) {
    for (const p of by[tier].filament) {
      let score = 0;
      const presetType = (p.filament_type ?? '').trim().toUpperCase();
      const presetColor = normalizeColorForCompare(p.filament_colour ?? '');
      if (reqType && presetType && reqType === presetType) score += 10;
      if (reqColor && presetColor) {
        if (presetColor === reqColor) score += 5;
        else if (colorsAreSimilar(p.filament_colour ?? '', required.color)) score += 2;
      }
      score += TIER_BONUS[tier];
      if (best == null || score > best.score) {
        best = { ref: { source: p.source, id: p.id }, score };
      }
    }
  }
  // Fall back to plain priority pick if every preset scored 0+tier (i.e. no
  // metadata matched). The fallback is exactly the single-color default —
  // first preset in the highest-priority non-empty tier.
  if (best == null) return pickDefault(by, 'filament');
  return best.ref;
}

// Inline spinner for the filament-requirements query. The backend runs a
// preview slice on first open of an unsliced project file (cached after);
// on a complex multi-color model that's a real slice — multi-second to
// multi-minute. The spinner shows elapsed seconds, polls the sidecar's
// --pipe progress (via /slicer/preview-progress proxy) for live stage +
// percent, and after ~5s surfaces a "this is a one-time slice — repeat
// opens are instant" note so users don't worry it'll be slow forever.
//
// requestId: a UUID generated by the modal when the filament-requirements
// fetch starts. Forwarded to the sidecar via the API call AND used here
// to poll the matching progress snapshot. Same id, two consumers.
function FilamentAnalysisSpinner({
  requestId,
  sourceName,
}: {
  requestId: string;
  sourceName: string;
}) {
  const { t } = useTranslation();
  const { showPersistentToast, dismissToast } = useToast();
  const [elapsed, setElapsed] = useState(0);
  const [progress, setProgress] = useState<SliceJobProgress | null>(null);
  // Defensive decode — see prettifyFilename comment in SliceJobTrackerContext.
  let prettyName = sourceName;
  try {
    prettyName = decodeURIComponent(sourceName);
  } catch {
    /* keep raw on malformed encoding */
  }

  // Elapsed-time tick.
  useEffect(() => {
    const startedAt = Date.now();
    const id = setInterval(() => setElapsed(Math.floor((Date.now() - startedAt) / 1000)), 1000);
    return () => clearInterval(id);
  }, []);

  // Progress polling — once per second while the spinner is mounted.
  // Mirrors the slice-job tracker's cadence. Sidecar 404s during the
  // race window between fetch start and progressStore.start() are
  // swallowed by the API method (returns null) so we keep polling.
  useEffect(() => {
    let cancelled = false;
    const id = setInterval(async () => {
      if (cancelled) return;
      const snap = await api.getPreviewSliceProgress(requestId);
      if (!cancelled && snap) setProgress(snap);
    }, 1000);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [requestId]);

  // Mirror the spinner's contents into a persistent toast so the user
  // sees activity even when their cursor is elsewhere on the page.
  // Dismissed in the parent's effect when the requirements arrive.
  const toastId = `slice-preview-${requestId}`;
  useEffect(() => {
    const hasUseful = progress && progress.stage && progress.total_percent > 0;
    const elapsedStr = formatElapsed(elapsed);
    if (hasUseful) {
      showPersistentToast(
        toastId,
        t(
          'slice.previewWithProgress',
          'Analyzing {{name}} — {{stage}} ({{percent}}%) — {{elapsed}}',
          {
            name: prettyName,
            stage: progress!.stage,
            percent: Math.min(100, Math.max(0, Math.round(progress!.total_percent))),
            elapsed: elapsedStr,
          },
        ),
        'loading',
      );
    } else {
      showPersistentToast(
        toastId,
        t('slice.previewToast', 'Analyzing {{name}} — {{elapsed}}', {
          name: prettyName,
          elapsed: elapsedStr,
        }),
        'loading',
      );
    }
    return () => {
      dismissToast(toastId);
    };
  }, [elapsed, progress, prettyName, showPersistentToast, dismissToast, t, toastId]);

  const stage = progress?.stage;
  const percent = progress?.total_percent;
  const inlineLabel =
    stage && typeof percent === 'number' && percent > 0
      ? `${stage} (${Math.min(100, Math.max(0, Math.round(percent)))}%)`
      : t('slice.analyzingPlateFilaments', 'Analyzing plate filaments…');
  return (
    <div className="flex flex-col gap-1 text-bambu-gray text-sm py-2">
      <div className="flex items-center gap-2">
        <Loader2 className="w-4 h-4 animate-spin" />
        {inlineLabel}
        <span className="text-xs tabular-nums">{elapsed}s</span>
      </div>
      {elapsed >= 5 && (
        <div className="text-xs text-bambu-gray/70 pl-6">
          {t(
            'slice.analyzingPlateFilamentsHint',
            'Running a preview slice to discover which AMS slots this plate uses. Cached after — re-opening is instant.',
          )}
        </div>
      )}
    </div>
  );
}

function formatElapsed(seconds: number): string {
  const s = Math.max(0, Math.floor(seconds));
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  const remS = s % 60;
  if (m < 60) return `${m}m ${remS}s`;
  const h = Math.floor(m / 60);
  const remM = m % 60;
  return `${h}h ${remM}m`;
}

export function SliceModal({ source, onClose }: SliceModalProps) {
  const { t } = useTranslation();
  const { trackJob } = useSliceJobTracker();

  const [printerPreset, setPrinterPreset] = useState<PresetRef | null>(null);
  const [processPreset, setProcessPreset] = useState<PresetRef | null>(null);
  // One filament ref per plate slot, in plate order. For STL / single-plate /
  // single-color sources this is a one-element array; multi-color 3MFs get one
  // entry per AMS slot the plate uses. Pre-pick (effect below) initialises
  // each slot from the source plate's required (type, colour).
  const [filamentPresets, setFilamentPresets] = useState<(PresetRef | null)[]>([]);
  // Bundle dispatch (alternative to the preset triplet). When non-null, the
  // SliceModal hides the cloud/local/standard preset dropdowns and shows
  // bundle-scoped pickers (process + per-slot filament from the chosen
  // bundle's contents). Submit routes through the backend's bundle dispatch
  // (`SliceRequest.bundle`) which skips PresetRef resolution.
  //
  // We do NOT restore the bundle id from localStorage on mount — a stale
  // id would put the modal in "bundle mode with empty dropdowns" if the
  // bundle was deleted between sessions. Instead, the unified preset-source
  // toggle reads ``last-bundle-id`` only when the user explicitly clicks
  // "Bundle", and validates against the current ``bundlesQuery.data`` first.
  const [selectedBundleId, setSelectedBundleId] = useState<string | null>(null);
  const [bundleProcessName, setBundleProcessName] = useState<string | null>(null);
  const [bundleFilamentNames, setBundleFilamentNames] = useState<(string | null)[]>([]);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  // Owner filter for the preset dropdowns — same 3-state model as the
  // ProfilesPage filter (``all`` / ``custom`` ("My presets") /
  // ``builtin``). Persisted in localStorage so a user who always picks
  // their own profiles doesn't have to flip the toggle on every modal
  // open. Default ``all`` keeps the existing behaviour for first-time
  // users / fresh browsers.
  const [filterOwner, setFilterOwner] = useState<OwnerFilter>(() => {
    if (typeof localStorage === 'undefined') return 'all';
    try {
      const stored = localStorage.getItem('bamdude:slice-modal:filter-owner');
      return stored === 'custom' || stored === 'builtin' ? stored : 'all';
    } catch {
      return 'all';
    }
  });
  useEffect(() => {
    if (typeof localStorage === 'undefined') return;
    try {
      localStorage.setItem('bamdude:slice-modal:filter-owner', filterOwner);
    } catch {
      /* private mode / quota — silently skip */
    }
  }, [filterOwner]);

  // Remember the last-picked bundle id so reopening the modal in bundle
  // mode doesn't make the user re-pick from the dropdown every time.
  // Only writes — restoration happens on explicit "Bundle" click via
  // ``handlePresetSourceChange`` (with a freshness check against the
  // current ``bundlesQuery.data``).
  useEffect(() => {
    if (typeof localStorage === 'undefined' || selectedBundleId == null) return;
    try {
      localStorage.setItem('bamdude:slice-modal:last-bundle-id', selectedBundleId);
    } catch {
      /* private mode / quota — silently skip */
    }
  }, [selectedBundleId]);

  // Bed plate override sent to the slicer as ``--curr-bed-type``. Default
  // ``Textured PEI Plate`` matches the factory plate shipped with X1C / P1S
  // / H2D — the modern Bambu lineup the majority of our users own. A1 /
  // A1-mini owners who run Smooth PEI (SuperTack) will flip this once and
  // localStorage persists the pick, so subsequent slices land on the right
  // adhesion temps without re-clicking. Without this override the slicer
  // CLI defaults to "Cool Plate", which produces the wrong first-layer bed
  // temperature for any X1/A1 user with a default plate.
  const [bedType, setBedType] = useState<BedType>(() => {
    if (typeof localStorage === 'undefined') return 'Textured PEI Plate';
    try {
      const stored = localStorage.getItem('bamdude:slice-modal:bed-type');
      const allowed: BedType[] = [
        'Cool Plate',
        'Engineering Plate',
        'High Temp Plate',
        'Textured PEI Plate',
        'Supertack Plate',
      ];
      return (allowed as string[]).includes(stored ?? '') ? (stored as BedType) : 'Textured PEI Plate';
    } catch {
      return 'Textured PEI Plate';
    }
  });
  useEffect(() => {
    if (typeof localStorage === 'undefined') return;
    try {
      localStorage.setItem('bamdude:slice-modal:bed-type', bedType);
    } catch {
      /* private mode / quota — silently skip */
    }
  }, [bedType]);
  // When the owner filter narrows the visible set, any current selection
  // that no longer matches must drop to null — otherwise the dropdown
  // would render an out-of-section value the user can no longer see in
  // the list, and clicking Slice would submit a preset they didn't
  // (re-)pick under the new filter. Pre-pick effect won't re-fire because
  // its dep is presetsQuery.data only.
  // null = plate not yet picked (or single-plate / non-3MF — picker is skipped
  // and we'll backfill 1 at submit time). Set to a 1-indexed plate number once
  // the user picks one (or implicitly for single-plate sources).
  const [selectedPlate, setSelectedPlate] = useState<number | null>(null);

  // Per-job slicer picker (B.4 follow-up). Visible only when both sidecars
  // are reachable — otherwise the global preferred_slicer setting is the
  // sole sensible target and the picker would just be misleading. The pick
  // is persisted per (source kind, source id) in localStorage so re-slicing
  // the same file defaults to the user's last choice; first-time defaults
  // to the global preferred_slicer.
  const settingsQuery = useQuery({
    queryKey: ['settings'],
    queryFn: api.getSettings,
    staleTime: 60_000,
  });
  // Backend caches the health response per (kind, url) for 30 s — these
  // two queries hit the network at most once per modal open, even if the
  // SliceModal re-mounts a few times during the user's flow.
  const orcaHealthQuery = useQuery({
    queryKey: ['slicerHealth', 'orcaslicer'],
    queryFn: () => api.getSlicerHealth('orcaslicer'),
    staleTime: 30_000,
    retry: false,
  });
  const bambuHealthQuery = useQuery({
    queryKey: ['slicerHealth', 'bambu_studio'],
    queryFn: () => api.getSlicerHealth('bambu_studio'),
    staleTime: 30_000,
    retry: false,
  });
  const orcaHealthy = orcaHealthQuery.data?.healthy === true;
  const bambuHealthy = bambuHealthQuery.data?.healthy === true;
  const showSlicerPicker = orcaHealthy && bambuHealthy;

  const slicerPickStorageKey = `bamdude:slicer-pick:${source.kind}:${source.id}`;
  const [pickedSlicer, setPickedSlicer] = useState<SlicerKind | null>(() => {
    if (typeof localStorage === 'undefined') return null;
    try {
      const stored = localStorage.getItem(slicerPickStorageKey);
      return stored === 'orcaslicer' || stored === 'bambu_studio' ? stored : null;
    } catch {
      return null;
    }
  });
  // Auto-select / default pick logic. Two cases beyond "user already picked":
  //
  //   1. Only one sidecar is healthy → lock to that one. Stops the modal
  //      from defaulting to a global preferred_slicer that's offline,
  //      and visually reflects "you have one option" in the picker cards.
  //
  //   2. Both healthy → first-time default to the global preferred_slicer
  //      (same as before). Subsequent renders keep whatever the user picked
  //      (persisted via localStorage on a separate effect).
  //
  // Also: if the user previously picked a sidecar that is now offline,
  // override to the healthy one. Otherwise the Slice button would silently
  // submit an offline-targeted request and fail at backend.
  useEffect(() => {
    if (orcaHealthQuery.isLoading || bambuHealthQuery.isLoading) return;
    const onlyOrca = orcaHealthy && !bambuHealthy;
    const onlyBambu = bambuHealthy && !orcaHealthy;
    if (onlyOrca) {
      if (pickedSlicer !== 'orcaslicer') setPickedSlicer('orcaslicer');
      return;
    }
    if (onlyBambu) {
      if (pickedSlicer !== 'bambu_studio') setPickedSlicer('bambu_studio');
      return;
    }
    if (!showSlicerPicker) return; // neither healthy — leave as-is
    if (pickedSlicer != null) return;
    const preferred = settingsQuery.data?.preferred_slicer;
    if (preferred === 'orcaslicer' || preferred === 'bambu_studio') {
      setPickedSlicer(preferred);
    } else {
      setPickedSlicer('bambu_studio');
    }
  }, [
    showSlicerPicker,
    orcaHealthy,
    bambuHealthy,
    orcaHealthQuery.isLoading,
    bambuHealthQuery.isLoading,
    pickedSlicer,
    settingsQuery.data?.preferred_slicer,
  ]);
  // Persist user's pick across modal opens.
  useEffect(() => {
    if (pickedSlicer == null || typeof localStorage === 'undefined') return;
    try {
      localStorage.setItem(slicerPickStorageKey, pickedSlicer);
    } catch {
      /* private mode / quota — silently skip */
    }
  }, [pickedSlicer, slicerPickStorageKey]);

  const platesQuery = useQuery({
    queryKey: ['slicePlates', source.kind, source.id],
    queryFn: async () => {
      if (source.kind === 'libraryFile') {
        return api.getLibraryFilePlates(source.id);
      }
      return api.getArchivePlates(source.id);
    },
    staleTime: 60_000,
  });

  const isMultiPlate =
    !!platesQuery.data?.is_multi_plate && (platesQuery.data?.plates?.length ?? 0) > 1;
  // Single-plate / non-3MF / fetch failure: skip the picker, default to plate 1
  // at submit time so the backend's existing default behaviour is preserved.
  // Multi-plate: auto-pick the first plate on load so the filament-reqs +
  // presets queries fire immediately (the inline ``<SlicePlateSelector>``
  // lets the user reassign without blocking the rest of the modal).
  const needsPlatePicker = isMultiPlate && selectedPlate == null;
  useEffect(() => {
    if (!isMultiPlate || selectedPlate != null) return;
    const first = platesQuery.data?.plates?.[0]?.index;
    if (first != null) setSelectedPlate(first);
  }, [isMultiPlate, selectedPlate, platesQuery.data]);

  // Per-plate filament requirements via the same endpoint the print/schedule
  // modal uses. Reusing it here keeps the SliceModal honest with whatever
  // logic that endpoint applies (slice_info parsing, preview-slice fallback,
  // future enhancements for unsliced project files, dual-nozzle fields, etc.)
  // instead of duplicating extraction. plate_id is always sent: single-plate
  // falls through to plate 1 server-side; multi-plate uses the user's pick.
  const effectivePlateId = selectedPlate ?? 1;
  // Generate a request_id per (source, plate) pair so the backend's
  // preview-slice and the FilamentAnalysisSpinner's progress poll share the
  // same id. useMemo keeps it stable across renders within the same pair;
  // switching plates regenerates so a stale poll doesn't bleed progress
  // between plates.
  const previewRequestId = useMemo(() => {
    const random =
      typeof crypto !== 'undefined' && 'randomUUID' in crypto
        ? crypto.randomUUID()
        : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    // Tag the id with the (source, plate) so logs/Network panel show which
    // pair owns the poll. Also lets the lint rule see the deps in use.
    return `${source.kind}-${source.id}-p${effectivePlateId}-${random}`;
  }, [source.kind, source.id, effectivePlateId]);
  const filamentReqsQuery = useQuery({
    queryKey: ['sliceFilamentReqs', source.kind, source.id, effectivePlateId],
    queryFn: async () => {
      if (source.kind === 'libraryFile') {
        return api.getLibraryFileFilamentRequirements(source.id, effectivePlateId, previewRequestId);
      }
      return api.getArchiveFilamentRequirements(source.id, effectivePlateId, previewRequestId);
    },
    enabled: !needsPlatePicker,
    staleTime: 60_000,
  });

  // Filament slot list for the active plate. Falls back to one synthetic slot
  // for STL/STEP and any "no metadata available" case so the modal still
  // works (single dropdown, mono-color slice).
  const filamentSlots = useMemo<PlateFilament[]>(() => {
    const reqs = filamentReqsQuery.data?.filaments ?? [];
    if (reqs.length > 0) return reqs as PlateFilament[];
    return [
      { slot_id: 1, type: '', color: '', used_grams: 0, used_meters: 0 },
    ];
  }, [filamentReqsQuery.data]);

  const presetsQuery = useQuery({
    queryKey: ['slicerPresets'],
    queryFn: () => api.getSlicerPresets(),
    staleTime: 60_000,
    // Don't fetch presets while the plate picker is on screen — saves a
    // round-trip if the user cancels out of the plate step.
    enabled: !platesQuery.isLoading && !needsPlatePicker,
  });

  // Imported Printer Preset Bundles (.bbscfg). Empty list when no sidecar
  // configured / no bundles imported yet; the bundle picker hides itself
  // in that case so users without bundles see the original modal layout.
  const bundlesQuery = useQuery({
    queryKey: ['slicerBundles'],
    queryFn: api.listSlicerBundles,
    staleTime: 60_000,
    enabled: !platesQuery.isLoading && !needsPlatePicker,
    // Bundle listing is a hard 503 when the sidecar is offline; don't
    // retry tight loops in that case.
    retry: false,
  });
  const selectedBundle: SlicerBundle | null = useMemo(() => {
    if (!selectedBundleId || !bundlesQuery.data) return null;
    return bundlesQuery.data.find((b) => b.id === selectedBundleId) ?? null;
  }, [selectedBundleId, bundlesQuery.data]);
  const isBundleMode = selectedBundle != null;

  // Unified mode toggle for the preset-source row. Switching to "manual"
  // clears the selected bundle (so all the cloud/local/standard machinery
  // re-renders); switching to "bundle" picks the last-used bundle id from
  // localStorage if it's still present in the current list, otherwise
  // falls back to the first available bundle. We never set a stale id.
  const handlePresetSourceChange = (next: 'manual' | 'bundle') => {
    if (next === 'manual') {
      setSelectedBundleId(null);
      return;
    }
    const bundles = bundlesQuery.data ?? [];
    if (bundles.length === 0) return;
    let candidate: string | null = null;
    if (typeof localStorage !== 'undefined') {
      try {
        const stored = localStorage.getItem('bamdude:slice-modal:last-bundle-id');
        if (stored && bundles.some((b) => b.id === stored)) candidate = stored;
      } catch {
        /* private mode / quota — fall through to first */
      }
    }
    setSelectedBundleId(candidate ?? bundles[0].id);
  };

  // Printer / process pre-pick: see SLICE_MODAL_TIER_ORDER. Runs once when
  // presets first arrive; subsequent re-renders preserve any manual choice.
  useEffect(() => {
    if (!presetsQuery.data) return;
    if (printerPreset == null) setPrinterPreset(pickDefault(presetsQuery.data, 'printer'));
    if (processPreset == null) setProcessPreset(pickDefault(presetsQuery.data, 'process'));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [presetsQuery.data]);

  // Filament pre-pick: re-runs whenever the active filament-slot count
  // changes (plate selection, single-plate metadata arriving). For each slot
  // we score every available filament preset against the slot's required
  // (type, colour) and keep the highest match. Slot count mismatch → reset
  // and re-pick everything; same length → preserve any user override.
  useEffect(() => {
    if (!presetsQuery.data) return;
    const data = presetsQuery.data;
    setFilamentPresets((current) => {
      if (current.length === filamentSlots.length && current.every((r) => r != null)) {
        return current;
      }
      return filamentSlots.map((slot) =>
        pickFilamentForSlot(data, { type: slot.type, color: slot.color }),
      );
    });
  }, [presetsQuery.data, filamentSlots]);

  // Bundle-mode auto-pick: when the user picks a bundle (or the slot count
  // changes after the picker is open), default the process to the bundle's
  // first listed process and every filament slot to the bundle's first
  // listed filament. Plain string match — bundles store delta files keyed
  // by user preset name, no scoring needed since the user picks per-slot
  // afterwards if the default is wrong.
  useEffect(() => {
    if (!selectedBundle) {
      // Reset bundle picks when bundle is cleared so re-selection
      // re-defaults rather than carrying stale values.
      setBundleProcessName(null);
      setBundleFilamentNames([]);
      return;
    }
    setBundleProcessName((current) => {
      // Preserve a manual pick if it still exists in the bundle; otherwise
      // re-default. Same shape as the preset auto-pick effect above.
      if (current && selectedBundle.process.includes(current)) return current;
      return selectedBundle.process[0] ?? null;
    });
    setBundleFilamentNames((current) => {
      if (current.length === filamentSlots.length && current.every((n) => n != null)) {
        return current;
      }
      const fallback = selectedBundle.filament[0] ?? null;
      return filamentSlots.map((_, i) => current[i] ?? fallback);
    });
  }, [selectedBundle, filamentSlots]);

  // Clear any current preset selection that no longer satisfies the
  // owner filter (resolves the picked id against the loaded preset
  // catalogue and drops the value if the resolved entry — or its absence
  // — fails ``matchesOwnerFilter``). The pre-pick effects above won't
  // re-fire because their dep is presetsQuery.data, so the dropdowns
  // surface the placeholder option until the user re-picks under the
  // narrower filter.
  useEffect(() => {
    if (!presetsQuery.data) return;
    const data = presetsQuery.data;
    const lookup = (slot: Slot, ref: PresetRef | null): UnifiedPreset | null => {
      if (!ref) return null;
      return data[ref.source][slot].find((p) => p.id === ref.id) ?? null;
    };
    const dropIfStale = (slot: Slot, ref: PresetRef | null): PresetRef | null => {
      const found = lookup(slot, ref);
      if (!found) return ref;
      return matchesOwnerFilter(found, filterOwner) ? ref : null;
    };
    setPrinterPreset((cur) => dropIfStale('printer', cur));
    setProcessPreset((cur) => dropIfStale('process', cur));
    setFilamentPresets((cur) => cur.map((ref) => dropIfStale('filament', ref)));
  }, [filterOwner, presetsQuery.data]);

  const enqueueMutation = useMutation({
    mutationFn: async () => {
      let body: SliceRequest;
      if (isBundleMode) {
        // Bundle dispatch path. The selected bundle's first printer is the
        // implicit printer choice (every .bbscfg carries exactly one).
        if (
          !selectedBundle ||
          !bundleProcessName ||
          bundleFilamentNames.length === 0 ||
          bundleFilamentNames.some((n) => n == null)
        ) {
          throw new Error(t('slice.bundleAllRequired', 'Bundle process and every filament slot must be picked'));
        }
        const bundleSpec: SliceBundleSpec = {
          bundle_id: selectedBundle.id,
          printer_name: selectedBundle.printer[0] ?? selectedBundle.printer_preset_name,
          process_name: bundleProcessName,
          filament_names: bundleFilamentNames as string[],
        };
        body = {
          bundle: bundleSpec,
          ...(selectedPlate != null ? { plate: selectedPlate } : {}),
          ...(pickedSlicer != null ? { slicer: pickedSlicer } : {}),
          bed_type: bedType,
        };
      } else {
        if (
          !printerPreset ||
          !processPreset ||
          filamentPresets.length === 0 ||
          filamentPresets.some((r) => r == null)
        ) {
          throw new Error(t('slice.allPresetsRequired', 'All presets must be selected'));
        }
        body = {
          printer_preset: printerPreset,
          process_preset: processPreset,
          // The first slot also goes into the legacy singular field so the
          // backend's older callers / clients keep behaving the same — the
          // backend validator prefers `filament_presets` when both are set.
          filament_preset: filamentPresets[0] as PresetRef,
          filament_presets: filamentPresets as PresetRef[],
          // Always send a concrete plate number when the source is multi-plate;
          // omit otherwise so the backend default applies for STL / single-plate
          // 3MF sources where the concept doesn't apply.
          ...(selectedPlate != null ? { plate: selectedPlate } : {}),
          // Per-job slicer override. Only sent when the picker is actually
          // visible to the user (both sidecars healthy) AND the user picked
          // something — otherwise the global preferred_slicer setting decides.
          ...(pickedSlicer != null ? { slicer: pickedSlicer } : {}),
          // Bed plate override → sidecar's ``bedType`` form field →
          // ``--curr-bed-type`` CLI flag.
          bed_type: bedType,
        };
      }
      if (source.kind === 'libraryFile') {
        return api.sliceLibraryFile(source.id, body);
      }
      return api.sliceArchive(source.id, body);
    },
    onSuccess: (enqueue) => {
      trackJob(enqueue.job_id, source.kind, source.filename);
      onClose();
    },
    onError: (err: unknown) => {
      const msg = err instanceof Error ? err.message : String(err);
      setErrorMessage(msg);
    },
  });

  // Cross-printer re-slicing is supported: the slicer CLI re-slices a 3MF
  // for whatever printer the chosen bundle/preset names — bed, kinematics,
  // nozzle count and start-gcode all come from the target. No source/target
  // model gate (#1325 cross-printer; upstream Bambuddy ed27b27a).

  // Slice button gates only on a complete picker selection. Multi-plate
  // sources also need an explicit plate pick so the slicer (and the
  // filament-reqs query that feeds the dropdowns) target the right plate.
  // Tier mode also gates on the preview-slice / embedded-metadata read
  // having succeeded (``filamentReqsQuery.isSuccess``) — until then, the
  // synthetic single-slot fallback would have auto-enabled the button on
  // opaque defaults before the slicer returned the real slot map.
  // Upstream Bambuddy commit a64cfbbd.
  const isReady = isBundleMode
    ? selectedBundle != null &&
      bundleProcessName != null &&
      bundleFilamentNames.length > 0 &&
      bundleFilamentNames.every((n) => n != null) &&
      (!isMultiPlate || selectedPlate != null)
    : printerPreset != null &&
      processPreset != null &&
      filamentReqsQuery.isSuccess &&
      filamentPresets.length > 0 &&
      filamentPresets.every((r) => r != null) &&
      (!isMultiPlate || selectedPlate != null);
  const isEnqueuing = enqueueMutation.isPending;

  // Single-screen layout: preset picker
  // picker. While the plates query is in-flight we still render the shell
  // because the presets query is gated on it; the loader covers both.
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"
      onClick={() => {
        if (!isEnqueuing) onClose();
      }}
    >
      <div
        className="w-full max-w-xl max-h-[85vh] flex flex-col rounded-lg bg-bambu-dark-secondary border border-bambu-dark-tertiary/60"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex-shrink-0 flex items-start justify-between gap-3 px-4 pt-4 pb-3 border-b border-bambu-dark-tertiary/40">
          <div className="min-w-0">
            <h3 className="text-white font-medium flex items-center gap-2">
              <Cog className="w-4 h-4" />
              {t('slice.title', 'Slice model')}
            </h3>
            <p className="text-xs text-bambu-gray mt-1 truncate" title={source.filename}>
              {source.filename}
              {selectedPlate != null
                ? ` • ${t('archives.platePicker.plateLabel', { index: selectedPlate })}`
                : ''}
            </p>
          </div>
          <button
            onClick={onClose}
            disabled={isEnqueuing}
            className="flex-shrink-0 text-bambu-gray hover:text-white transition-colors disabled:opacity-50"
            aria-label={t('common.close', 'Close')}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {/* Inline plate picker for multi-plate sources. Visually mirrors
              ``PrintModal/PlateSelector`` so the slice + print flows feel
              consistent (vertical paginator strip + big details card).
              Renders above the other sections so the user sees their
              plate context first; switching plates re-keys the
              filament-reqs query so the dropdowns below realign to the
              new plate's required (type, color) automatically. */}
          {isMultiPlate && platesQuery.data && (
            <SlicePlateSelector
              plates={platesQuery.data.plates}
              selectedPlate={selectedPlate}
              onSelect={setSelectedPlate}
              disabled={isEnqueuing}
            />
          )}
          {/* Preset listing loader — printer/process dropdowns can't render
              without it. Plate query reuses the same spinner since it's
              also blocking. */}
          {(platesQuery.isLoading || presetsQuery.isLoading) && (
            <div className="flex items-center gap-2 text-bambu-gray text-sm">
              <Loader2 className="w-4 h-4 animate-spin" />
              {t('slice.loadingPresets', 'Loading presets…')}
            </div>
          )}

          {presetsQuery.isError && (
            <div className="text-sm text-red-400" role="alert">
              {t(
                'slice.presetsLoadFailed',
                'Failed to load presets. Open Settings → Profiles to import them, or sign in to Bambu Cloud.',
              )}
            </div>
          )}

          {presetsQuery.data && (
            <>
              <CloudStatusBanner status={presetsQuery.data.cloud_status} />
              {/* Slicer picker — two big card-buttons matching the
                  "Filament Tracking" pattern in Settings. Each card carries
                  its own live health status (version / offline / checking)
                  pulled from the same shared React Query cache. Always
                  renders so the user sees what's available even when only
                  one sidecar is up; offline ones are disabled and can't
                  be picked. */}
              <SlicerPicker
                value={pickedSlicer}
                onChange={setPickedSlicer}
                disabled={isEnqueuing}
              />
              {/* Bed plate picker — five values from BambuStudio's
                  ``curr_bed_type`` enum. Always sent on slice (the slicer
                  CLI's silent fallback to "Cool Plate" is the bug we're
                  fixing for STL / pure-3MF inputs). Default Textured PEI
                  matches the factory plate on X1C / P1S / H2D; A1 owners
                  flip to SuperTack once and localStorage persists. */}
              <BedTypePicker value={bedType} onChange={setBedType} disabled={isEnqueuing} />
              {/* Unified preset-source control: top-level Manual/Bundle
                  toggle (only when at least one .bbscfg is imported), plus
                  a sub-control that swaps between the 3-state owner
                  filter (Manual mode) and the bundle picker (Bundle mode).
                  Replaces the previous two side-by-side widgets that left
                  the owner filter visibly active in bundle mode where it
                  had no effect. */}
              <PresetSourceControl
                mode={isBundleMode ? 'bundle' : 'manual'}
                onModeChange={handlePresetSourceChange}
                ownerFilter={filterOwner}
                onOwnerFilterChange={setFilterOwner}
                bundles={bundlesQuery.data ?? []}
                selectedBundleId={selectedBundleId}
                onBundleChange={setSelectedBundleId}
                disabled={isEnqueuing}
              />
              {/* removed inline `bundlesQuery.data && length > 0` BundlePicker —
                  PresetSourceControl renders the picker only when bundles exist */}
              {/* Preset triplet — hidden when a bundle is selected so the
                  user only sees one tier at a time. The bundle's process +
                  filament dropdowns render below in their stead. */}
              {!isBundleMode && (
                <>
                  <PresetDropdown
                    label={t('slice.printer', 'Printer profile')}
                    slot="printer"
                    data={presetsQuery.data}
                    value={printerPreset}
                    onChange={setPrinterPreset}
                    disabled={isEnqueuing}
                    ownerFilter={filterOwner}
                  />
                  <PresetDropdown
                    label={t('slice.process', 'Process profile')}
                    slot="process"
                    data={presetsQuery.data}
                    value={processPreset}
                    onChange={setProcessPreset}
                    disabled={isEnqueuing}
                    ownerFilter={filterOwner}
                  />
                </>
              )}
              {isBundleMode && selectedBundle && (
                <>
                  {/* Bundle's printer is implicit (each .bbscfg has exactly
                      one). Show it as a read-only label so the user can
                      verify the printer they're slicing for. */}
                  <div>
                    <label className="block text-sm text-bambu-gray mb-1">
                      {t('slice.printer', 'Printer profile')}
                    </label>
                    <div className="px-3 py-2 rounded-md bg-bambu-dark/40 border border-bambu-dark-tertiary text-white text-sm">
                      {selectedBundle.printer_preset_name}
                    </div>
                  </div>
                  <BundleStringDropdown
                    label={t('slice.process', 'Process profile')}
                    options={selectedBundle.process}
                    value={bundleProcessName}
                    onChange={setBundleProcessName}
                    disabled={isEnqueuing}
                  />
                </>
              )}
              {/* Filament reqs may need a server-side preview-slice for
                  unsliced project files (single-pass, then cached). Show a
                  scoped spinner so the user sees the printer/process
                  dropdowns instead of an opaque "Loading presets…" wait. */}
              {filamentReqsQuery.isLoading ? (
                <FilamentAnalysisSpinner
                  requestId={previewRequestId}
                  sourceName={source.filename}
                />
              ) : isBundleMode && selectedBundle ? (
                filamentSlots.map((slot, idx) => {
                  const isUsed = slot.used_in_plate !== false;
                  const baseLabel =
                    filamentSlots.length > 1
                      ? t('slice.filamentSlot', {
                          index: idx + 1,
                          type: slot.type,
                          defaultValue: `Filament ${idx + 1} (${slot.type || ''})`,
                        })
                      : t('slice.filament', 'Filament profile');
                  const label = isUsed
                    ? baseLabel
                    : `${baseLabel} ${t('slice.notUsedByPlate', '— not used by this plate')}`;
                  return (
                    <BundleStringDropdown
                      key={`bundle-filament-${idx}`}
                      label={label}
                      options={selectedBundle.filament}
                      value={bundleFilamentNames[idx] ?? null}
                      onChange={(name) =>
                        setBundleFilamentNames((current) => {
                          const next =
                            current.length === filamentSlots.length
                              ? [...current]
                              : filamentSlots.map((_, i) => current[i] ?? null);
                          next[idx] = name;
                          return next;
                        })
                      }
                      disabled={isEnqueuing || !isUsed}
                      swatchColor={filamentSlots.length > 1 ? slot.color : undefined}
                    />
                  );
                })
              ) : (
                filamentSlots.map((slot, idx) => {
                  // Slots flagged by the backend as not used by the
                  // picked plate are auto-picked from project metadata
                  // and disabled — the slicer CLI still needs a
                  // profile per project slot, but the user shouldn't
                  // have to think about slots their plate doesn't
                  // paint with. used_in_plate defaults to true when
                  // missing (sliced 3MFs and the no-flag legacy path).
                  const isUsed = slot.used_in_plate !== false;
                  const baseLabel =
                    filamentSlots.length > 1
                      ? t('slice.filamentSlot', {
                          index: idx + 1,
                          type: slot.type,
                          defaultValue: `Filament ${idx + 1} (${slot.type || ''})`,
                        })
                      : t('slice.filament', 'Filament profile');
                  const label = isUsed
                    ? baseLabel
                    : `${baseLabel} ${t('slice.notUsedByPlate', '— not used by this plate')}`;
                  return (
                    <PresetDropdown
                      key={`filament-${idx}`}
                      label={label}
                      slot="filament"
                      data={presetsQuery.data}
                      value={filamentPresets[idx] ?? null}
                      onChange={(ref) =>
                        setFilamentPresets((current) => {
                          const next = current.length === filamentSlots.length
                            ? [...current]
                            : filamentSlots.map((_, i) => current[i] ?? null);
                          next[idx] = ref;
                          return next;
                        })
                      }
                      disabled={isEnqueuing || !isUsed}
                      swatchColor={filamentSlots.length > 1 ? slot.color : undefined}
                      ownerFilter={filterOwner}
                    />
                  );
                })
              )}
            </>
          )}

          {errorMessage && (
            <div className="text-sm text-red-400 bg-red-900/20 border border-red-900/40 rounded p-2" role="alert">
              {errorMessage}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex-shrink-0 flex justify-end gap-2 px-4 py-3 border-t border-bambu-dark-tertiary/40">
          <button
            type="button"
            onClick={onClose}
            disabled={isEnqueuing}
            className="px-3 py-1.5 text-sm rounded-md border border-bambu-dark-tertiary text-bambu-gray hover:text-white hover:border-bambu-gray transition-colors disabled:opacity-50"
          >
            {t('common.cancel', 'Cancel')}
          </button>
          <button
            type="button"
            onClick={() => {
              setErrorMessage(null);
              enqueueMutation.mutate();
            }}
            disabled={!isReady || isEnqueuing}
            className="px-3 py-1.5 text-sm rounded-md bg-bambu-green hover:bg-bambu-green/90 text-bambu-dark font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {isEnqueuing ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                {t('slice.enqueuing', 'Submitting slice job…')}
              </>
            ) : (
              t('slice.action', 'Slice')
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

function CloudStatusBanner({ status }: { status: SlicerCloudStatus }) {
  const { t } = useTranslation();
  if (status === 'ok') return null;

  // Map each non-ok status to the appropriate icon + tone. None of these are
  // hard errors — the user can still slice using local + standard presets,
  // so we use info / warn styling rather than error red.
  const config: Record<Exclude<SlicerCloudStatus, 'ok'>, { tone: string; icon: typeof Cloud; key: string; fallback: string }> = {
    not_authenticated: {
      tone: 'border-bambu-dark-tertiary/40 bg-bambu-dark text-bambu-gray',
      icon: Cloud,
      key: 'slice.cloud.notAuthenticated',
      fallback: 'Sign in to Bambu Cloud (Settings → Profiles → Cloud) to see your cloud presets.',
    },
    expired: {
      tone: 'border-amber-700/40 bg-amber-900/20 text-amber-200',
      icon: CloudOff,
      key: 'slice.cloud.expired',
      fallback: 'Bambu Cloud session expired — sign in again to refresh your cloud presets.',
    },
    unreachable: {
      tone: 'border-bambu-dark-tertiary/40 bg-bambu-dark text-bambu-gray',
      icon: CloudOff,
      key: 'slice.cloud.unreachable',
      fallback: 'Bambu Cloud is unreachable right now. Local and standard presets still work.',
    },
  };
  const { tone, icon: Icon, key, fallback } = config[status];
  return (
    <div className={`flex items-start gap-2 text-xs rounded-md border p-2 ${tone}`} role="status">
      <Icon className="w-4 h-4 flex-shrink-0 mt-0.5" />
      <span>{t(key, fallback)}</span>
    </div>
  );
}
