"""3MF gcode post-processor — patches gcode inside a 3MF archive.

Current patches:
    * **mesh_mode_fast_check_off** — comments out ``M970`` / ``M970.3``
      vibration-probe commands in the start gcode of every plate. These
      commands run the "Quick Vibration Check" (belt-tension pre-flight)
      before each print. Commenting them out is the only way to skip the
      check — there is no runtime MQTT parameter for it.

The patcher operates on a **copy** of the source file. The original in
the library / archive dir is never modified so ``file_hash`` /
``content_hash`` stays valid and dedup continues to work. The dispatch
pipeline passes the patched copy to FTP upload and records
``source_content_hash`` (original) + ``applied_patches`` on the archive
row so the chain-of-custody mechanism in ``services/archive.py`` keeps
everything linked.
"""

from __future__ import annotations

import hashlib
import logging
import re
import shutil
import tempfile
import zipfile
from pathlib import Path

logger = logging.getLogger(__name__)

# Regex: uncommented M970 or M970.3 command (with optional parameters).
# Anchored to line start with optional leading whitespace.
_M970_RE = re.compile(r"^(\s*)(M970(?:\.3)?\s.*)", re.MULTILINE)

# Slicer embeds the full machine_start_gcode / machine_end_gcode as a
# single-line parameter comment at the top of the gcode file, e.g.:
#   ; machine_start_gcode = G28\nM140 S60\n...M970.3 Q1...\n...
# These lines must NOT be patched — they're metadata for re-slicing, not
# executed gcode. We mask them before the regex pass and unmask after.
_PARAM_GCODE_RE = re.compile(r"^; machine_(start|end)_gcode = .*$", re.MULTILINE)
_MASK_PREFIX = "; __BAMDUDE_MASKED_PARAM_"


def _mask_param_gcode(gcode: str) -> tuple[str, list[str]]:
    """Replace `; machine_*_gcode = ...` lines with placeholders."""
    placeholders: list[str] = []

    def _replacer(m: re.Match) -> str:
        placeholders.append(m.group(0))
        return f"{_MASK_PREFIX}{len(placeholders) - 1}__"

    masked = _PARAM_GCODE_RE.sub(_replacer, gcode)
    return masked, placeholders


def _unmask_param_gcode(gcode: str, placeholders: list[str]) -> str:
    """Restore masked parameter lines."""
    for i, original in enumerate(placeholders):
        gcode = gcode.replace(f"{_MASK_PREFIX}{i}__", original)
    return gcode


def _comment_m970(gcode: str) -> tuple[str, int]:
    """Comment out uncommented M970/M970.3 lines.

    Returns (patched_gcode, count_of_lines_commented).
    """
    count = 0

    def _replacer(m: re.Match) -> str:
        nonlocal count
        count += 1
        # Preserve leading whitespace, prepend semicolon.
        return f"{m.group(1)};{m.group(2)}"

    patched = _M970_RE.sub(_replacer, gcode)
    return patched, count


def _md5_bytes(data: bytes) -> str:
    """Compute MD5 hex digest (used by Bambu firmware for gcode verification)."""
    return hashlib.md5(data, usedforsecurity=False).hexdigest()


def patch_mesh_mode_fast_check(source_3mf: Path) -> tuple[Path, list[str]]:
    """Comment out M970 vibration-probe commands in *source_3mf*.

    If no uncommented M970 lines are found in any plate gcode → the file
    is already "patched" (e.g. generated by swaplist.app with "vibration
    only once") → returns ``(source_3mf, [])`` (passthrough, no temp file).

    Otherwise copies the 3MF to a temp file, patches all plate gcodes,
    recalculates their MD5 sidecar files, and returns
    ``(temp_path, ["mesh_mode_fast_check_off"])``.

    **The caller is responsible for deleting the temp file** after upload.
    """
    if not source_3mf.exists():
        logger.warning("[PATCHER] Source file not found: %s", source_3mf)
        return source_3mf, []

    # Scan first — avoid the copy if nothing to patch.
    gcode_entries: list[str] = []
    needs_patch = False
    try:
        with zipfile.ZipFile(source_3mf, "r") as zf:
            for name in zf.namelist():
                if re.match(r"Metadata/[Pp]late_\d+\.gcode$", name):
                    gcode_entries.append(name)

            for entry in gcode_entries:
                raw = zf.read(entry).decode("utf-8", errors="replace")
                # Mask parameter lines so they don't trigger false positives.
                masked, _ = _mask_param_gcode(raw)
                if _M970_RE.search(masked):
                    needs_patch = True
                    break
    except (zipfile.BadZipFile, OSError) as e:
        logger.warning("[PATCHER] Cannot read 3MF %s: %s", source_3mf, e)
        return source_3mf, []

    if not needs_patch:
        logger.debug("[PATCHER] No uncommented M970 lines in %s — passthrough", source_3mf.name)
        return source_3mf, []

    # Copy to temp and patch in-place inside the ZIP.
    temp_dir = tempfile.mkdtemp(prefix="bamdude_patch_")
    temp_path = Path(temp_dir) / source_3mf.name
    shutil.copy2(source_3mf, temp_path)

    total_commented = 0
    try:
        with zipfile.ZipFile(temp_path, "r") as zf_read:
            all_entries = zf_read.namelist()
            entry_data: dict[str, bytes] = {}
            for name in all_entries:
                entry_data[name] = zf_read.read(name)

        # Patch gcode entries + recalculate MD5 sidecars.
        for entry in gcode_entries:
            raw = entry_data[entry].decode("utf-8", errors="replace")
            masked, placeholders = _mask_param_gcode(raw)
            patched, count = _comment_m970(masked)
            total_commented += count
            if count > 0:
                unmasked = _unmask_param_gcode(patched, placeholders)
                patched_bytes = unmasked.encode("utf-8")
                entry_data[entry] = patched_bytes
                # Update the MD5 sidecar (e.g. Metadata/plate_1.gcode.md5).
                md5_entry = f"{entry}.md5"
                if md5_entry in entry_data:
                    entry_data[md5_entry] = _md5_bytes(patched_bytes).encode("ascii")
                    logger.debug("[PATCHER] Updated %s", md5_entry)

        # Rewrite the ZIP with patched content.
        with zipfile.ZipFile(temp_path, "w", compression=zipfile.ZIP_DEFLATED) as zf_write:
            for name in all_entries:
                zf_write.writestr(name, entry_data[name])

    except Exception:
        # Clean up temp on failure and fall back to original.
        logger.exception("[PATCHER] Failed to patch %s — falling back to original", source_3mf.name)
        shutil.rmtree(temp_dir, ignore_errors=True)
        return source_3mf, []

    logger.info(
        "[PATCHER] Patched %s: commented %d M970 line(s) across %d plate(s) → %s",
        source_3mf.name,
        total_commented,
        len(gcode_entries),
        temp_path,
    )
    return temp_path, ["mesh_mode_fast_check_off"]
