"""3MF gcode post-processor — patches gcode inside a 3MF archive.

Current transforms:
    * **mesh_mode_fast_check_off** — comments out ``M970`` / ``M970.3``
      vibration-probe commands in the start gcode of every plate. These
      commands run the "Quick Vibration Check" (belt-tension pre-flight)
      before each print. Commenting them out is the only way to skip the
      check — there is no runtime MQTT parameter for it.
    * **gcode_injection** (#422) — splices operator-defined start/end
      snippets into one specific plate's gcode at
      ``; MACHINE_START_GCODE_END`` (start) / EOF (end), with
      ``{placeholder}`` substitution from the 3MF gcode header.

When both transforms run on the same dispatch, ``apply_3mf_transforms``
opens + rewrites the 3MF **once** instead of twice. Each transform is a
function on the in-memory ``entry_data`` dict; md5 sidecars are
recomputed only for plates that were actually modified.

The patcher operates on a **copy** of the source file. The original in
the library / archive dir is never modified so ``file_hash`` /
``content_hash`` stays valid and dedup continues to work. The dispatch
pipeline passes the patched copy to FTP upload and records
``source_content_hash`` (original) + ``applied_patches`` on the archive
row so the chain-of-custody mechanism in ``services/archive.py`` keeps
everything linked.
"""

from __future__ import annotations

import hashlib
import logging
import re
import shutil
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class GcodeInjectionSpec:
    """Per-dispatch G-code injection request (#422).

    ``plate_id`` is 1-indexed; ``start_gcode`` / ``end_gcode`` are the
    operator-defined snippets resolved from ``gcode_snippets`` for the
    target printer model. Either side can be empty/None.
    """

    plate_id: int
    start_gcode: str | None
    end_gcode: str | None


# Regex: uncommented M970 or M970.3 command (with optional parameters).
# Anchored to line start with optional leading whitespace.
_M970_RE = re.compile(r"^(\s*)(M970(?:\.3)?\s.*)", re.MULTILINE)

# Slicer embeds the full machine_start_gcode / machine_end_gcode as a
# single-line parameter comment at the top of the gcode file, e.g.:
#   ; machine_start_gcode = G28\nM140 S60\n...M970.3 Q1...\n...
# These lines must NOT be patched — they're metadata for re-slicing, not
# executed gcode. We mask them before the regex pass and unmask after.
_PARAM_GCODE_RE = re.compile(r"^; machine_(start|end)_gcode = .*$", re.MULTILINE)
_MASK_PREFIX = "; __BAMDUDE_MASKED_PARAM_"


def _mask_param_gcode(gcode: str) -> tuple[str, list[str]]:
    """Replace `; machine_*_gcode = ...` lines with placeholders."""
    placeholders: list[str] = []

    def _replacer(m: re.Match) -> str:
        placeholders.append(m.group(0))
        return f"{_MASK_PREFIX}{len(placeholders) - 1}__"

    masked = _PARAM_GCODE_RE.sub(_replacer, gcode)
    return masked, placeholders


def _unmask_param_gcode(gcode: str, placeholders: list[str]) -> str:
    """Restore masked parameter lines."""
    for i, original in enumerate(placeholders):
        gcode = gcode.replace(f"{_MASK_PREFIX}{i}__", original)
    return gcode


def _comment_m970(gcode: str) -> tuple[str, int]:
    """Comment out uncommented M970/M970.3 lines.

    Returns (patched_gcode, count_of_lines_commented).
    """
    count = 0

    def _replacer(m: re.Match) -> str:
        nonlocal count
        count += 1
        # Preserve leading whitespace, prepend semicolon.
        return f"{m.group(1)};{m.group(2)}"

    patched = _M970_RE.sub(_replacer, gcode)
    return patched, count


def _md5_bytes(data: bytes) -> str:
    """Compute MD5 hex digest (used by Bambu firmware for gcode verification)."""
    return hashlib.md5(data, usedforsecurity=False).hexdigest()


def patch_mesh_mode_fast_check(source_3mf: Path) -> tuple[Path, list[str]]:
    """Comment out M970 vibration-probe commands in *source_3mf*.

    If no uncommented M970 lines are found in any plate gcode → the file
    is already "patched" (e.g. generated by swaplist.app with "vibration
    only once") → returns ``(source_3mf, [])`` (passthrough, no temp file).

    Otherwise copies the 3MF to a temp file, patches all plate gcodes,
    recalculates their MD5 sidecar files, and returns
    ``(temp_path, ["mesh_mode_fast_check_off"])``.

    **The caller is responsible for deleting the temp file** after upload.
    """
    if not source_3mf.exists():
        logger.warning("[PATCHER] Source file not found: %s", source_3mf)
        return source_3mf, []

    # Scan first — avoid the copy if nothing to patch.
    gcode_entries: list[str] = []
    needs_patch = False
    try:
        with zipfile.ZipFile(source_3mf, "r") as zf:
            for name in zf.namelist():
                if re.match(r"Metadata/[Pp]late_\d+\.gcode$", name):
                    gcode_entries.append(name)

            for entry in gcode_entries:
                raw = zf.read(entry).decode("utf-8", errors="replace")
                # Mask parameter lines so they don't trigger false positives.
                masked, _ = _mask_param_gcode(raw)
                if _M970_RE.search(masked):
                    needs_patch = True
                    break
    except (zipfile.BadZipFile, OSError) as e:
        logger.warning("[PATCHER] Cannot read 3MF %s: %s", source_3mf, e)
        return source_3mf, []

    if not needs_patch:
        logger.debug("[PATCHER] No uncommented M970 lines in %s — passthrough", source_3mf.name)
        return source_3mf, []

    # Copy to temp and patch in-place inside the ZIP.
    temp_dir = tempfile.mkdtemp(prefix="bamdude_patch_")
    temp_path = Path(temp_dir) / source_3mf.name
    shutil.copy2(source_3mf, temp_path)

    total_commented = 0
    try:
        with zipfile.ZipFile(temp_path, "r") as zf_read:
            all_entries = zf_read.namelist()
            entry_data: dict[str, bytes] = {}
            for name in all_entries:
                entry_data[name] = zf_read.read(name)

        # Patch gcode entries + recalculate MD5 sidecars.
        for entry in gcode_entries:
            raw = entry_data[entry].decode("utf-8", errors="replace")
            masked, placeholders = _mask_param_gcode(raw)
            patched, count = _comment_m970(masked)
            total_commented += count
            if count > 0:
                unmasked = _unmask_param_gcode(patched, placeholders)
                patched_bytes = unmasked.encode("utf-8")
                entry_data[entry] = patched_bytes
                # Update the MD5 sidecar (e.g. Metadata/plate_1.gcode.md5).
                md5_entry = f"{entry}.md5"
                if md5_entry in entry_data:
                    entry_data[md5_entry] = _md5_bytes(patched_bytes).encode("ascii")
                    logger.debug("[PATCHER] Updated %s", md5_entry)

        # Rewrite the ZIP with patched content.
        with zipfile.ZipFile(temp_path, "w", compression=zipfile.ZIP_DEFLATED) as zf_write:
            for name in all_entries:
                zf_write.writestr(name, entry_data[name])

    except Exception:
        # Clean up temp on failure and fall back to original.
        logger.exception("[PATCHER] Failed to patch %s — falling back to original", source_3mf.name)
        shutil.rmtree(temp_dir, ignore_errors=True)
        return source_3mf, []

    logger.info(
        "[PATCHER] Patched %s: commented %d M970 line(s) across %d plate(s) → %s",
        source_3mf.name,
        total_commented,
        len(gcode_entries),
        temp_path,
    )
    return temp_path, ["mesh_mode_fast_check_off"]


def apply_3mf_transforms(
    source_3mf: Path,
    *,
    mesh_mode_fast_check_off: bool = False,
    gcode_injection: GcodeInjectionSpec | None = None,
) -> tuple[Path, list]:
    """Open the 3MF once, apply every requested transform, write once.

    Folds the M970-commenting pass and the gcode-injection pass into a
    single open/mutate/write cycle. Without this, dispatching a job that
    needs both transforms would unzip + rezip the 3MF twice (once per
    transform) and update md5 sidecars twice — wasted I/O on what can be
    a 50+ MB file.

    Returns ``(out_path, applied_patches)``.

    * ``out_path`` is ``source_3mf`` (passthrough) when no transform
      actually changed any byte (e.g. the operator toggled mesh-mode-fast
      off but the file already has every M970 commented — common with
      Swaplist exports). The caller can hand the source straight to FTP
      and skip the temp-file cleanup.
    * Otherwise it's a freshly-allocated temp file under
      ``tempfile.mkdtemp(prefix='bamdude_patch_')``; the caller is
      responsible for removing the parent dir after upload.
    * ``applied_patches`` is the list to feed into ``archive_print``'s
      ``applied_patches`` JSON column for chain-of-custody. Format mixes
      strings (legacy ``"mesh_mode_fast_check_off"``) and dicts (richer
      transforms like ``{"name": "gcode_injection", "plate_id": N}``).

    Failures fall back to the original source — never raise. A snippet
    typo or malformed 3MF can't take a print job down.
    """
    if not source_3mf.exists():
        logger.warning("[PATCHER] Source file not found: %s", source_3mf)
        return source_3mf, []

    if not mesh_mode_fast_check_off and gcode_injection is None:
        return source_3mf, []  # No-op — caller asked for no transforms.

    # Open once into memory so each transform can mutate the same dict.
    try:
        with zipfile.ZipFile(source_3mf, "r") as zf_read:
            all_entries = zf_read.namelist()
            entry_data: dict[str, bytes] = {name: zf_read.read(name) for name in all_entries}
    except (zipfile.BadZipFile, OSError) as e:
        logger.warning("[PATCHER] Cannot read 3MF %s: %s", source_3mf, e)
        return source_3mf, []

    plate_entries = [n for n in all_entries if re.match(r"Metadata/[Pp]late_\d+\.gcode$", n)]
    if not plate_entries:
        return source_3mf, []

    applied: list = []
    modified_plates: set[str] = set()

    if mesh_mode_fast_check_off:
        total_commented = 0
        for entry in plate_entries:
            raw = entry_data[entry].decode("utf-8", errors="replace")
            masked, placeholders = _mask_param_gcode(raw)
            patched, count = _comment_m970(masked)
            if count > 0:
                total_commented += count
                unmasked = _unmask_param_gcode(patched, placeholders)
                entry_data[entry] = unmasked.encode("utf-8")
                modified_plates.add(entry)
        if total_commented > 0:
            applied.append("mesh_mode_fast_check_off")
            logger.info(
                "[PATCHER] mesh_mode_fast_check_off: commented %d M970 line(s) across %d plate(s)",
                total_commented,
                len(plate_entries),
            )

    if gcode_injection is not None:
        # Imported lazily to avoid a hard import cycle (gcode_injector
        # itself doesn't depend on gcode_patcher, but tests stub the
        # injector and we don't want patcher import to drag it in).
        from backend.app.services.gcode_injector import (
            _inject_start_at_marker,
            _parse_3mf_gcode_header,
            _substitute_placeholders,
        )

        target_name = f"Metadata/plate_{gcode_injection.plate_id}.gcode"
        if target_name not in entry_data:
            # Fall back to first plate so a stale plate_id from the queue
            # item still produces a useful injection rather than silently
            # no-op'ing — matches inject_gcode_into_3mf's own fallback.
            target_name = plate_entries[0]
        start_gc = (gcode_injection.start_gcode or "").strip()
        end_gc = (gcode_injection.end_gcode or "").strip()
        if start_gc or end_gc:
            try:
                content = entry_data[target_name].decode("utf-8", errors="replace")
                header = _parse_3mf_gcode_header(content)
                if start_gc:
                    content = _inject_start_at_marker(content, _substitute_placeholders(start_gc, header))
                if end_gc:
                    content = content.rstrip("\n") + "\n" + _substitute_placeholders(end_gc, header) + "\n"
                entry_data[target_name] = content.encode("utf-8")
                modified_plates.add(target_name)
                applied.append({"name": "gcode_injection", "plate_id": gcode_injection.plate_id})
                logger.info(
                    "[PATCHER] gcode_injection applied to %s (start=%d, end=%d)",
                    target_name,
                    len(start_gc),
                    len(end_gc),
                )
            except Exception as exc:
                # Don't take the print down on snippet typos / malformed 3MF.
                logger.warning("[PATCHER] gcode_injection failed for %s: %s", target_name, exc)

    if not modified_plates:
        return source_3mf, []

    # Recompute md5 sidecars only for the plates we actually touched.
    for entry in modified_plates:
        md5_entry = f"{entry}.md5"
        if md5_entry in entry_data:
            entry_data[md5_entry] = _md5_bytes(entry_data[entry]).encode("ascii")

    temp_dir = tempfile.mkdtemp(prefix="bamdude_patch_")
    temp_path = Path(temp_dir) / source_3mf.name
    try:
        # Copy first so non-deflate metadata (timestamps etc.) lines up
        # with the original; then rewrite with mutated entry_data.
        shutil.copy2(source_3mf, temp_path)
        with zipfile.ZipFile(temp_path, "w", compression=zipfile.ZIP_DEFLATED) as zf_write:
            for name in all_entries:
                zf_write.writestr(name, entry_data[name])
    except Exception:
        logger.exception("[PATCHER] Failed to write transformed 3MF %s", source_3mf.name)
        shutil.rmtree(temp_dir, ignore_errors=True)
        return source_3mf, []

    return temp_path, applied
